// Auto-generated by DeclarationResolver
// Resolved 4 declarations from 3 files

import Foundation
import SwiftUI

enum AppCornerRadius {
    static let small: CGFloat = 8
    static let medium: CGFloat = 14
    static let large: CGFloat = 20
}

enum AchievementDefinition: String, CaseIterable {
    case firstSolo = "first_solo"
    case ironWill = "iron_will"
    case marathon = "marathon"
    case eagleEye = "eagle_eye"
    case perfectFlight = "perfect_flight"
    case mockMaster = "mock_master"
    case masteryAirLaw = "mastery_551"
    case masteryHumanPerformance = "mastery_552"
    case masteryMeteorology = "mastery_553"
    case masteryCommunications = "mastery_554"
    case masteryPrinciplesOfFlight = "mastery_555"
    case masteryOperationalProcedures = "mastery_556"
    case masteryMassBalance = "mastery_557"
    case masteryPerformance = "mastery_558"
    case masteryFlightPlanning = "mastery_559"
    case masteryAirframe = "mastery_560"
    case masteryInstrumentation = "mastery_528"
    case masteryGeneralNav = "mastery_501"
    case masteryRadioNav = "mastery_500"
    case nightOwl = "night_owl"
    case earlyBird = "early_bird"
    case comebackKid = "comeback_kid"
    case askTheInstructor = "ask_the_instructor"
    case memoryPalace = "memory_palace"
    
    var displayName: String {
        switch self {
        case .firstSolo: return "First Solo"
        case .ironWill: return "Iron Will"
        case .marathon: return "Marathon"
        case .eagleEye: return "Eagle Eye"
        case .perfectFlight: return "Perfect Flight"
        case .mockMaster: return "Mock Master"
        case .masteryAirLaw: return "Air Law Master"
        case .masteryHumanPerformance: return "Human Performance Master"
        case .masteryMeteorology: return "Meteorology Master"
        case .masteryCommunications: return "Communications Master"
        case .masteryPrinciplesOfFlight: return "Principles of Flight Master"
        case .masteryOperationalProcedures: return "Operational Procedures Master"
        case .masteryMassBalance: return "Mass & Balance Master"
        case .masteryPerformance: return "Performance Master"
        case .masteryFlightPlanning: return "Flight Planning Master"
        case .masteryAirframe: return "Airframe Master"
        case .masteryInstrumentation: return "Instrumentation Master"
        case .masteryGeneralNav: return "General Navigation Master"
        case .masteryRadioNav: return "Radio Navigation Master"
        case .nightOwl: return "Night Owl"
        case .earlyBird: return "Early Bird"
        case .comebackKid: return "Comeback Kid"
        case .askTheInstructor: return "Ask the Instructor"
        case .memoryPalace: return "Memory Palace"
        }
    }
    
    var description: String {
        switch self {
        case .firstSolo: return "Complete your first study session"
        case .ironWill: return "Maintain a 7-day study streak"
        case .marathon: return "Maintain a 30-day study streak"
        case .eagleEye: return "Answer 10 questions correctly in a row"
        case .perfectFlight: return "Complete a session with 20+ questions, all correct"
        case .mockMaster: return "Pass a mock exam"
        case .masteryAirLaw: return "Master all Air Law questions"
        case .masteryHumanPerformance: return "Master all Human Performance questions"
        case .masteryMeteorology: return "Master all Meteorology questions"
        case .masteryCommunications: return "Master all Communications questions"
        case .masteryPrinciplesOfFlight: return "Master all Principles of Flight questions"
        case .masteryOperationalProcedures: return "Master all Operational Procedures questions"
        case .masteryMassBalance: return "Master all Mass & Balance questions"
        case .masteryPerformance: return "Master all Performance questions"
        case .masteryFlightPlanning: return "Master all Flight Planning questions"
        case .masteryAirframe: return "Master all Airframe questions"
        case .masteryInstrumentation: return "Master all Instrumentation questions"
        case .masteryGeneralNav: return "Master all General Navigation questions"
        case .masteryRadioNav: return "Master all Radio Navigation questions"
        case .nightOwl: return "Study between 10 PM and 4 AM"
        case .earlyBird: return "Study between 4 AM and 7 AM"
        case .comebackKid: return "Master a question you got wrong 3+ times"
        case .askTheInstructor: return "Create 10 mnemonics"
        case .memoryPalace: return "Create 20 mnemonics"
        }
    }
    
    var icon: String {
        switch self {
        case .firstSolo: return "airplane.departure"
        case .ironWill: return "flame"
        case .marathon: return "figure.run"
        case .eagleEye: return "eye"
        case .perfectFlight: return "star.fill"
        case .mockMaster: return "checkmark.seal.fill"
        case .masteryAirLaw, .masteryHumanPerformance, .masteryMeteorology, .masteryCommunications,
             .masteryPrinciplesOfFlight, .masteryOperationalProcedures, .masteryMassBalance,
             .masteryPerformance, .masteryFlightPlanning, .masteryAirframe, .masteryInstrumentation,
             .masteryGeneralNav, .masteryRadioNav:
            return "graduationcap.fill"
        case .nightOwl: return "moon.stars.fill"
        case .earlyBird: return "sunrise.fill"
        case .comebackKid: return "arrow.uturn.up"
        case .askTheInstructor: return "lightbulb.fill"
        case .memoryPalace: return "brain.head.profile"
        }
    }
    
    static func masteryAchievement(for categoryId: Int64) -> AchievementDefinition? {
        AchievementDefinition(rawValue: "mastery_\(categoryId)")
    }
}

struct AchievementsView: View {
    @Environment(\.dependencies) private var deps
    @State private var achievements: [AchievementDefinition] = AchievementDefinition.allCases
    @State private var unlockedIds: Set<String> = []
    
    var body: some View {
        ScrollView {
            LazyVGrid(columns: [GridItem(.adaptive(minimum: 150))], spacing: 16) {
                ForEach(achievements, id: \.rawValue) { achievement in
                    AchievementCard(
                        achievement: achievement,
                        isUnlocked: unlockedIds.contains(achievement.rawValue)
                    )
                }
            }
            .padding()
        }
        .navigationTitle("Achievements")
        .onAppear {
            loadAchievements()
        }
    }
    
    private func loadAchievements() {
        guard let deps = deps else { return }
        achievements = AchievementDefinition.allCases
        unlockedIds = Set((try? deps.databaseManager.fetchAchievements().map(\.id)) ?? [])
    }
}

struct AchievementCard: View {
    let achievement: AchievementDefinition
    let isUnlocked: Bool
    
    var body: some View {
        VStack(spacing: 12) {
            ZStack {
                Circle()
                    .fill(isUnlocked ? Color.yellow.opacity(0.2) : Color(.systemGray6))
                    .frame(width: 80, height: 80)
                
                Image(systemName: achievement.icon)
                    .font(.system(size: 36))
                    .foregroundColor(isUnlocked ? .yellow : .secondary)
            }
            
            VStack(spacing: 4) {
                Text(achievement.displayName)
                    .font(.subheadline.weight(.semibold))
                    .multilineTextAlignment(.center)
                    .foregroundColor(isUnlocked ? .primary : .secondary)
                
                Text(achievement.description)
                    .font(.caption)
                    .foregroundColor(.secondary)
                    .multilineTextAlignment(.center)
                    .lineLimit(2)
            }
        }
        .padding()
        .background(.regularMaterial)
        .cornerRadius(AppCornerRadius.medium)
        .opacity(isUnlocked ? 1.0 : 0.6)
    }
}

